name: nightscoutbartus
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.putridumx }}
          password: ${{ secrets.dckr_pat_7Z8tafGAqT-RqEke-YU9WtgpZnw }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.putridumx }}/nightscoutbartus:latest
          cache-from: type=registry,ref=${{ secrets.putridumx }}/simplewhale:buildcache
          cache-to: type=registry,ref=${{ secrets.putridumx }}/nightscoutbartus:buildcache,mode=max
