# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nightscoutbartus

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: nightscoutbartus
      uses: docker/nightscoutbartus-action@v1

    - name: nightscoutbartus
      uses: docker/putridumx-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.putridumx }}
        password: ${{ secrets.dckr_pat_7Z8tafGAqT-RqEke-YU9WtgpZnw }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8f6c6ffb6f564b39a98df393119b7921 }}/nightscout/cgm-remote-monitor:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nightscoutbartus'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_44dafa7e796849bf9550b7d0eb180fab }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8f6c6ffb6f564b39a98df393119b7921 }}/nightscout/cgm-remote-monitor:${{ github.sha }}'
